# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Starlight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starlight
  pod 'Alamofire', '4.1.0'
  pod 'INTULocationManager', '4.2.0'
  pod 'SwiftyJSON', '3.1.3'

  target 'StarlightTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
